//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalAgenda.ServiceReferenceAsmx {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contacto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Contacto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceAsmx.AgendaContactosService1Soap")]
    public interface AgendaContactosService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ProyectoFinalAgenda.ServiceReferenceAsmx.HelloWorldResponse HelloWorld(ProyectoFinalAgenda.ServiceReferenceAsmx.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ProyectoFinalAgenda.ServiceReferenceAsmx.HelloWorldResponse> HelloWorldAsync(ProyectoFinalAgenda.ServiceReferenceAsmx.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetContactosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetContactos", ReplyAction="*")]
        ProyectoFinalAgenda.ServiceReferenceAsmx.GetContactosResponse GetContactos(ProyectoFinalAgenda.ServiceReferenceAsmx.GetContactosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetContactos", ReplyAction="*")]
        System.Threading.Tasks.Task<ProyectoFinalAgenda.ServiceReferenceAsmx.GetContactosResponse> GetContactosAsync(ProyectoFinalAgenda.ServiceReferenceAsmx.GetContactosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetContactoPorIdResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetContactoPorId", ReplyAction="*")]
        ProyectoFinalAgenda.ServiceReferenceAsmx.GetContactoPorIdResponse GetContactoPorId(ProyectoFinalAgenda.ServiceReferenceAsmx.GetContactoPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetContactoPorId", ReplyAction="*")]
        System.Threading.Tasks.Task<ProyectoFinalAgenda.ServiceReferenceAsmx.GetContactoPorIdResponse> GetContactoPorIdAsync(ProyectoFinalAgenda.ServiceReferenceAsmx.GetContactoPorIdRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento c del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarContacto", ReplyAction="*")]
        ProyectoFinalAgenda.ServiceReferenceAsmx.AgregarContactoResponse AgregarContacto(ProyectoFinalAgenda.ServiceReferenceAsmx.AgregarContactoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarContacto", ReplyAction="*")]
        System.Threading.Tasks.Task<ProyectoFinalAgenda.ServiceReferenceAsmx.AgregarContactoResponse> AgregarContactoAsync(ProyectoFinalAgenda.ServiceReferenceAsmx.AgregarContactoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento c del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditarContacto", ReplyAction="*")]
        ProyectoFinalAgenda.ServiceReferenceAsmx.EditarContactoResponse EditarContacto(ProyectoFinalAgenda.ServiceReferenceAsmx.EditarContactoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditarContacto", ReplyAction="*")]
        System.Threading.Tasks.Task<ProyectoFinalAgenda.ServiceReferenceAsmx.EditarContactoResponse> EditarContactoAsync(ProyectoFinalAgenda.ServiceReferenceAsmx.EditarContactoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarContacto", ReplyAction="*")]
        bool EliminarContacto(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarContacto", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> EliminarContactoAsync(int id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ProyectoFinalAgenda.ServiceReferenceAsmx.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ProyectoFinalAgenda.ServiceReferenceAsmx.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProyectoFinalAgenda.ServiceReferenceAsmx.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ProyectoFinalAgenda.ServiceReferenceAsmx.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContactosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContactos", Namespace="http://tempuri.org/", Order=0)]
        public ProyectoFinalAgenda.ServiceReferenceAsmx.GetContactosRequestBody Body;
        
        public GetContactosRequest() {
        }
        
        public GetContactosRequest(ProyectoFinalAgenda.ServiceReferenceAsmx.GetContactosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetContactosRequestBody {
        
        public GetContactosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContactosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContactosResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProyectoFinalAgenda.ServiceReferenceAsmx.GetContactosResponseBody Body;
        
        public GetContactosResponse() {
        }
        
        public GetContactosResponse(ProyectoFinalAgenda.ServiceReferenceAsmx.GetContactosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetContactosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProyectoFinalAgenda.ServiceReferenceAsmx.Contacto[] GetContactosResult;
        
        public GetContactosResponseBody() {
        }
        
        public GetContactosResponseBody(ProyectoFinalAgenda.ServiceReferenceAsmx.Contacto[] GetContactosResult) {
            this.GetContactosResult = GetContactosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContactoPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContactoPorId", Namespace="http://tempuri.org/", Order=0)]
        public ProyectoFinalAgenda.ServiceReferenceAsmx.GetContactoPorIdRequestBody Body;
        
        public GetContactoPorIdRequest() {
        }
        
        public GetContactoPorIdRequest(ProyectoFinalAgenda.ServiceReferenceAsmx.GetContactoPorIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetContactoPorIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetContactoPorIdRequestBody() {
        }
        
        public GetContactoPorIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContactoPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContactoPorIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProyectoFinalAgenda.ServiceReferenceAsmx.GetContactoPorIdResponseBody Body;
        
        public GetContactoPorIdResponse() {
        }
        
        public GetContactoPorIdResponse(ProyectoFinalAgenda.ServiceReferenceAsmx.GetContactoPorIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetContactoPorIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProyectoFinalAgenda.ServiceReferenceAsmx.Contacto GetContactoPorIdResult;
        
        public GetContactoPorIdResponseBody() {
        }
        
        public GetContactoPorIdResponseBody(ProyectoFinalAgenda.ServiceReferenceAsmx.Contacto GetContactoPorIdResult) {
            this.GetContactoPorIdResult = GetContactoPorIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarContactoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarContacto", Namespace="http://tempuri.org/", Order=0)]
        public ProyectoFinalAgenda.ServiceReferenceAsmx.AgregarContactoRequestBody Body;
        
        public AgregarContactoRequest() {
        }
        
        public AgregarContactoRequest(ProyectoFinalAgenda.ServiceReferenceAsmx.AgregarContactoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarContactoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProyectoFinalAgenda.ServiceReferenceAsmx.Contacto c;
        
        public AgregarContactoRequestBody() {
        }
        
        public AgregarContactoRequestBody(ProyectoFinalAgenda.ServiceReferenceAsmx.Contacto c) {
            this.c = c;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarContactoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarContactoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProyectoFinalAgenda.ServiceReferenceAsmx.AgregarContactoResponseBody Body;
        
        public AgregarContactoResponse() {
        }
        
        public AgregarContactoResponse(ProyectoFinalAgenda.ServiceReferenceAsmx.AgregarContactoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AgregarContactoResponseBody {
        
        public AgregarContactoResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditarContactoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditarContacto", Namespace="http://tempuri.org/", Order=0)]
        public ProyectoFinalAgenda.ServiceReferenceAsmx.EditarContactoRequestBody Body;
        
        public EditarContactoRequest() {
        }
        
        public EditarContactoRequest(ProyectoFinalAgenda.ServiceReferenceAsmx.EditarContactoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditarContactoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProyectoFinalAgenda.ServiceReferenceAsmx.Contacto c;
        
        public EditarContactoRequestBody() {
        }
        
        public EditarContactoRequestBody(ProyectoFinalAgenda.ServiceReferenceAsmx.Contacto c) {
            this.c = c;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditarContactoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditarContactoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProyectoFinalAgenda.ServiceReferenceAsmx.EditarContactoResponseBody Body;
        
        public EditarContactoResponse() {
        }
        
        public EditarContactoResponse(ProyectoFinalAgenda.ServiceReferenceAsmx.EditarContactoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EditarContactoResponseBody {
        
        public EditarContactoResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AgendaContactosService1SoapChannel : ProyectoFinalAgenda.ServiceReferenceAsmx.AgendaContactosService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AgendaContactosService1SoapClient : System.ServiceModel.ClientBase<ProyectoFinalAgenda.ServiceReferenceAsmx.AgendaContactosService1Soap>, ProyectoFinalAgenda.ServiceReferenceAsmx.AgendaContactosService1Soap {
        
        public AgendaContactosService1SoapClient() {
        }
        
        public AgendaContactosService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AgendaContactosService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgendaContactosService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgendaContactosService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoFinalAgenda.ServiceReferenceAsmx.HelloWorldResponse ProyectoFinalAgenda.ServiceReferenceAsmx.AgendaContactosService1Soap.HelloWorld(ProyectoFinalAgenda.ServiceReferenceAsmx.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ProyectoFinalAgenda.ServiceReferenceAsmx.HelloWorldRequest inValue = new ProyectoFinalAgenda.ServiceReferenceAsmx.HelloWorldRequest();
            inValue.Body = new ProyectoFinalAgenda.ServiceReferenceAsmx.HelloWorldRequestBody();
            ProyectoFinalAgenda.ServiceReferenceAsmx.HelloWorldResponse retVal = ((ProyectoFinalAgenda.ServiceReferenceAsmx.AgendaContactosService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoFinalAgenda.ServiceReferenceAsmx.HelloWorldResponse> ProyectoFinalAgenda.ServiceReferenceAsmx.AgendaContactosService1Soap.HelloWorldAsync(ProyectoFinalAgenda.ServiceReferenceAsmx.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoFinalAgenda.ServiceReferenceAsmx.HelloWorldResponse> HelloWorldAsync() {
            ProyectoFinalAgenda.ServiceReferenceAsmx.HelloWorldRequest inValue = new ProyectoFinalAgenda.ServiceReferenceAsmx.HelloWorldRequest();
            inValue.Body = new ProyectoFinalAgenda.ServiceReferenceAsmx.HelloWorldRequestBody();
            return ((ProyectoFinalAgenda.ServiceReferenceAsmx.AgendaContactosService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoFinalAgenda.ServiceReferenceAsmx.GetContactosResponse ProyectoFinalAgenda.ServiceReferenceAsmx.AgendaContactosService1Soap.GetContactos(ProyectoFinalAgenda.ServiceReferenceAsmx.GetContactosRequest request) {
            return base.Channel.GetContactos(request);
        }
        
        public ProyectoFinalAgenda.ServiceReferenceAsmx.Contacto[] GetContactos() {
            ProyectoFinalAgenda.ServiceReferenceAsmx.GetContactosRequest inValue = new ProyectoFinalAgenda.ServiceReferenceAsmx.GetContactosRequest();
            inValue.Body = new ProyectoFinalAgenda.ServiceReferenceAsmx.GetContactosRequestBody();
            ProyectoFinalAgenda.ServiceReferenceAsmx.GetContactosResponse retVal = ((ProyectoFinalAgenda.ServiceReferenceAsmx.AgendaContactosService1Soap)(this)).GetContactos(inValue);
            return retVal.Body.GetContactosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoFinalAgenda.ServiceReferenceAsmx.GetContactosResponse> ProyectoFinalAgenda.ServiceReferenceAsmx.AgendaContactosService1Soap.GetContactosAsync(ProyectoFinalAgenda.ServiceReferenceAsmx.GetContactosRequest request) {
            return base.Channel.GetContactosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoFinalAgenda.ServiceReferenceAsmx.GetContactosResponse> GetContactosAsync() {
            ProyectoFinalAgenda.ServiceReferenceAsmx.GetContactosRequest inValue = new ProyectoFinalAgenda.ServiceReferenceAsmx.GetContactosRequest();
            inValue.Body = new ProyectoFinalAgenda.ServiceReferenceAsmx.GetContactosRequestBody();
            return ((ProyectoFinalAgenda.ServiceReferenceAsmx.AgendaContactosService1Soap)(this)).GetContactosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoFinalAgenda.ServiceReferenceAsmx.GetContactoPorIdResponse ProyectoFinalAgenda.ServiceReferenceAsmx.AgendaContactosService1Soap.GetContactoPorId(ProyectoFinalAgenda.ServiceReferenceAsmx.GetContactoPorIdRequest request) {
            return base.Channel.GetContactoPorId(request);
        }
        
        public ProyectoFinalAgenda.ServiceReferenceAsmx.Contacto GetContactoPorId(int id) {
            ProyectoFinalAgenda.ServiceReferenceAsmx.GetContactoPorIdRequest inValue = new ProyectoFinalAgenda.ServiceReferenceAsmx.GetContactoPorIdRequest();
            inValue.Body = new ProyectoFinalAgenda.ServiceReferenceAsmx.GetContactoPorIdRequestBody();
            inValue.Body.id = id;
            ProyectoFinalAgenda.ServiceReferenceAsmx.GetContactoPorIdResponse retVal = ((ProyectoFinalAgenda.ServiceReferenceAsmx.AgendaContactosService1Soap)(this)).GetContactoPorId(inValue);
            return retVal.Body.GetContactoPorIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoFinalAgenda.ServiceReferenceAsmx.GetContactoPorIdResponse> ProyectoFinalAgenda.ServiceReferenceAsmx.AgendaContactosService1Soap.GetContactoPorIdAsync(ProyectoFinalAgenda.ServiceReferenceAsmx.GetContactoPorIdRequest request) {
            return base.Channel.GetContactoPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoFinalAgenda.ServiceReferenceAsmx.GetContactoPorIdResponse> GetContactoPorIdAsync(int id) {
            ProyectoFinalAgenda.ServiceReferenceAsmx.GetContactoPorIdRequest inValue = new ProyectoFinalAgenda.ServiceReferenceAsmx.GetContactoPorIdRequest();
            inValue.Body = new ProyectoFinalAgenda.ServiceReferenceAsmx.GetContactoPorIdRequestBody();
            inValue.Body.id = id;
            return ((ProyectoFinalAgenda.ServiceReferenceAsmx.AgendaContactosService1Soap)(this)).GetContactoPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoFinalAgenda.ServiceReferenceAsmx.AgregarContactoResponse ProyectoFinalAgenda.ServiceReferenceAsmx.AgendaContactosService1Soap.AgregarContacto(ProyectoFinalAgenda.ServiceReferenceAsmx.AgregarContactoRequest request) {
            return base.Channel.AgregarContacto(request);
        }
        
        public void AgregarContacto(ProyectoFinalAgenda.ServiceReferenceAsmx.Contacto c) {
            ProyectoFinalAgenda.ServiceReferenceAsmx.AgregarContactoRequest inValue = new ProyectoFinalAgenda.ServiceReferenceAsmx.AgregarContactoRequest();
            inValue.Body = new ProyectoFinalAgenda.ServiceReferenceAsmx.AgregarContactoRequestBody();
            inValue.Body.c = c;
            ProyectoFinalAgenda.ServiceReferenceAsmx.AgregarContactoResponse retVal = ((ProyectoFinalAgenda.ServiceReferenceAsmx.AgendaContactosService1Soap)(this)).AgregarContacto(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoFinalAgenda.ServiceReferenceAsmx.AgregarContactoResponse> ProyectoFinalAgenda.ServiceReferenceAsmx.AgendaContactosService1Soap.AgregarContactoAsync(ProyectoFinalAgenda.ServiceReferenceAsmx.AgregarContactoRequest request) {
            return base.Channel.AgregarContactoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoFinalAgenda.ServiceReferenceAsmx.AgregarContactoResponse> AgregarContactoAsync(ProyectoFinalAgenda.ServiceReferenceAsmx.Contacto c) {
            ProyectoFinalAgenda.ServiceReferenceAsmx.AgregarContactoRequest inValue = new ProyectoFinalAgenda.ServiceReferenceAsmx.AgregarContactoRequest();
            inValue.Body = new ProyectoFinalAgenda.ServiceReferenceAsmx.AgregarContactoRequestBody();
            inValue.Body.c = c;
            return ((ProyectoFinalAgenda.ServiceReferenceAsmx.AgendaContactosService1Soap)(this)).AgregarContactoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoFinalAgenda.ServiceReferenceAsmx.EditarContactoResponse ProyectoFinalAgenda.ServiceReferenceAsmx.AgendaContactosService1Soap.EditarContacto(ProyectoFinalAgenda.ServiceReferenceAsmx.EditarContactoRequest request) {
            return base.Channel.EditarContacto(request);
        }
        
        public void EditarContacto(ProyectoFinalAgenda.ServiceReferenceAsmx.Contacto c) {
            ProyectoFinalAgenda.ServiceReferenceAsmx.EditarContactoRequest inValue = new ProyectoFinalAgenda.ServiceReferenceAsmx.EditarContactoRequest();
            inValue.Body = new ProyectoFinalAgenda.ServiceReferenceAsmx.EditarContactoRequestBody();
            inValue.Body.c = c;
            ProyectoFinalAgenda.ServiceReferenceAsmx.EditarContactoResponse retVal = ((ProyectoFinalAgenda.ServiceReferenceAsmx.AgendaContactosService1Soap)(this)).EditarContacto(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoFinalAgenda.ServiceReferenceAsmx.EditarContactoResponse> ProyectoFinalAgenda.ServiceReferenceAsmx.AgendaContactosService1Soap.EditarContactoAsync(ProyectoFinalAgenda.ServiceReferenceAsmx.EditarContactoRequest request) {
            return base.Channel.EditarContactoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoFinalAgenda.ServiceReferenceAsmx.EditarContactoResponse> EditarContactoAsync(ProyectoFinalAgenda.ServiceReferenceAsmx.Contacto c) {
            ProyectoFinalAgenda.ServiceReferenceAsmx.EditarContactoRequest inValue = new ProyectoFinalAgenda.ServiceReferenceAsmx.EditarContactoRequest();
            inValue.Body = new ProyectoFinalAgenda.ServiceReferenceAsmx.EditarContactoRequestBody();
            inValue.Body.c = c;
            return ((ProyectoFinalAgenda.ServiceReferenceAsmx.AgendaContactosService1Soap)(this)).EditarContactoAsync(inValue);
        }
        
        public bool EliminarContacto(int id) {
            return base.Channel.EliminarContacto(id);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarContactoAsync(int id) {
            return base.Channel.EliminarContactoAsync(id);
        }
    }
}
